const BreakfastWraps = [
  {
    id: 1,
    title: 'Bacon, Egg and Cheese',
    category: 'breakfast',
    price: 8.00,
    img: '/client/src/assets/images/PicsArt_01-06-01.02.59.jpg',
    desc: `Crispy Bacon Slices, two eggs, shredded cheese and chipotle ranch sauce served in a 12" tortilla wrap`,
  },
  {
    id: 2,
    title: 'Chicken, Egg and Cheese',
    category: 'breakfast',
    price: 8.00,
    img: '/client/public/assets/images/IMG-20211122-WA0037.jpg',
    desc: `Chopped Chicken Breast, two eggs, shredded cheese and chipotle ranch sauce served in a 12" tortilla wrap`,
  },
  {
    id: 3,
    title: 'Turkey Sausage, Egg and Cheese',
    category: 'breakfast',
    price: 8.00,
    img: '/client/public/assets/images/IMG-20211122-WA0037.jpg',
    desc: `Turkey Pan Sausage, scrambled eggs, shredded cheese and chipotle ranch sauce served in a 12" tortilla wrap`,
  },
  {
    id: 4,
    title: 'Shrimp, Egg and Cheese',
    category: 'breakfast',
    price: 13.00,
    img: '/client/public/assets/images/IMG-20211122-WA0037.jpg',
    desc: `Grilled Jumbo Shrimp, scrambled eggs, shredded cheese and chipotle ranch sauce served in a 12" tortilla wrap`,
  },
  {
    id: 5,
    title: 'Veggie Medley',
    category: 'breakfast',
    price: 13.00,
    img: '/client/public/assets/images/IMG-20211122-WA0037.jpg',
    desc: `Sauteed Mushrooms, sauteed bell peppers, sauteed onions, shredded carrots, mixed greens, two eggs, shredded cheese and chipotle ranch sauce served in a 12" tortilla wrap`,
  },
  {
    id: 6,
    title: 'Steak, Egg and Cheese',
    category: 'breakfast',
    price: 15.00,
    img: '/client/public/assets/images/IMG-20211122-WA0037.jpg',
    desc: `USDA Choice Steak, scrambled eggs, shredded cheese and chipotle ranch sauce served in a 12" tortilla wrap`,
  },
  {
    id: 7,
    title: 'Breakfast Surf & Turf',
    category: 'breakfast',
    price: 15.00,
    img: '/client/public/assets/images/IMG-20211122-WA0037.jpg',
    desc: `USDA Choice Steak, scrambled eggs, shredded cheese and chipotle ranch sauce served in a 12" tortilla wrap`,
  },
];
export default BreakfastWraps;