const DeluxeOmelets = [
    {
      id: 1,
      title: 'Bacon Omelet',
      category: 'breakfast',
      price: 10.00,
      img: '/client/public/assets/images/IMG-20211122-WA0037.jpg',
      desc: `Bacon Slices and Bacon Crumbles, sauteed onions, sauteed pepper, diced tomatoes and shredded cheese`,
    },
    {
      id: 2,
      title: 'Chicken Omelet',
      category: 'breakfast',
      price: 10.00,
      img: '/client/public/assets/images/IMG-20211122-WA0037.jpg',
      desc: `Chopped Chicken Breast, sauteed onions, peppers and mushrooms with shredded cheese`,
    },
    {
      id: 3,
      title: 'Turkey Sausage Omelet',
      category: 'breakfast',
      price: 10.00,
      img: '/client/public/assets/images/IMG-20211122-WA0037.jpg',
      desc: `Turkey Pan Sausage, sauteed onions, sauteed peppers and shredded cheese`,
    },
    {
      id: 4,
      title: 'Seafood Omelet',
      category: 'breakfast',
      price: 15.00,
      img: '/client/public/assets/images/IMG-20211122-WA0037.jpg',
      desc: `Grilled Jumbo Shrimp and Imitation Crab Meat, sauteed onions, sauteed peppers and shredded cheese`,
    },
    {
      id: 5,
      title: 'Veggie Medley Omelet',
      category: 'breakfast',
      price: 15.00,
      img: '/client/public/assets/images/IMG-20211122-WA0037.jpg',
      desc: `Sauteed Mushrooms, Sauteed Bell Peppers, Sauteed Onions, shredded carrots, mixed greens and shredded cheese`,
    },
    {
      id: 6,
      title: 'Philly Cheesesteak Omelet',
      category: 'breakfast',
      price: 17.00,
      img: '/client/public/assets/images/IMG-20211122-WA0037.jpg',
      desc: `USDA Choice Steak, sauteed onions, peppers, and mushrooms with mozzarella cheese`,
    },
    {
      id: 7,
      title: 'Surf & Turf Omelet',
      category: 'breakfast',
      price: 17.00,
      img: '/client/public/assets/images/IMG-20211122-WA0037.jpg',
      desc: `USDA Choice Steak and Grilled Jumbo Shrimp, sauteed onions and shredded cheese`,
    },
  ];
  export default DeluxeOmelets;