const chickenWraps = [
  {
    id: 1,
    title: "Caesar Chicken",
    category: "lunch",
    price: 10.00,
    img: "/client/public/assets/images/IMG-20211122-WA0035.jpg",
    desc: `Chicken Breast, Lettuce, Grated Parmesan Cheese and Caesar Dressing.`,
  },
  {
    id: 2,
    title: "Buffalo Chicken",
    category: "lunch",
    price: 10.00,
    img: "/client/public/assets/images/IMG-20211122-WA0035.jpg",
    desc: `Chicken breast, lettuce, grated parmesan cheese and Buffalo Sauce with ranch dressing`,
  },
  {
    id: 3,
    title: "Jerk Chicken",
    category: "lunch",
    price: 10.00,
    img: "/client/public/assets/images/IMG-20211122-WA0035.jpg",
    desc: `Chicken Breast, Lettuce, Grated Parmesan Cheese, Shredded Carrots, Jalapeno Peppers and Jerk Seasoning with Chipotle Ranch Dressing`,
  },
  {
    id: 4,
    title: "Lemon Pepper Chicken",
    category: "lunch",
    price: 10.00,
    img: "/client/public/assets/images/IMG-20211122-WA0035.jpg",
    desc: `Chicken Breast, Lettuce, Grated Parmesan Cheese and Lemon Pepper Seasoning with Ranch Dressing`,
  },
  {
    id: 5,
    title: "Sweet Chili Thai Chicken",
    category: "lunch",
    price: 10.00,
    img: "/client/public/assets/images/IMG-20211122-WA0035.jpg",
    desc: `Chicken Breast, Lettuce, Grated Parmesan Cheese, Shredded Carrots, Jalapeno Peppers and Sweet Chili Thai Sauce`,
  },
  {
    id: 6,
    title: "Sweet Teriyaki Chicken",
    category: "lunch",
    price: 10.00,
    img: "/client/public/assets/images/IMG-20211122-WA0035.jpg",
    desc: `Chicken Breast, Sauteed Onions, Shredded Cheese and Sweet Teriyaki Sauce`,
  },
  {
    id: 7,
    title: "Philly Chicken",
    category: "lunch",
    price: 15.00,
    img: "/client/public/assets/images/IMG-20211122-WA0035.jpg",
    desc: `Chicken Breast, Sauteed Bell Peppers, Sauteed Mushrooms, Sauteed Onions, Mozzarella Cheese and Chipotle Ranch`,
  },
  {
    id: 8,
    title: "Philly Cheesesteak",
    category: "lunch",
    price: 17.00,
    img: "/client/public/assets/images/IMG-20211122-WA0035.jpg",
    desc: `USDA Choice Steak, Sauteed Bell Peppers, Mushrooms, Sauteed Onions, Mozzarella Cheese and Chipotle Ranch`,
  },
  {
    id: 9,
    title: "Very Berry Chicken",
    category: "lunch",
    price: 17.00,
    img: "/client/public/assets/images/IMG-20211122-WA0035.jpg",
    desc: `Grilled Chicken, Sliced Strawberries, Sundried Cranberries, Glazed Walnuts, Lettuce, Shredded Carrots, Banana Peppers, Raspberry Vinaigrette and Honey Mustard Dressing`,
  }
];
export default chickenWraps;
